/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LeftSider: typeof import('./src/components/LeftSider/LeftSider.vue')['default']
    RightSider: typeof import('./src/components/RightSider/RightSider.vue')['default']
    Transparency: typeof import('./src/components/Transparency/Transparency.vue')['default']
  }
}
